### ISSUE TITLE
Improper spelling

### ISSUE THREAD

**Issue by Jolley71717** [hologram-io/nova-hardware#1]
when a PPP session exists and the user executes the code `sudo hologram modem disconnect` the user is presented with the following:
`Checking for existing PPP sessions
Found existing PPP session on pid: [the pid that is found]`
The error shows up on the next line:
`Kiiing pid [the pid that is found] now`

**Comment by tzhenghao** [comment]
Hey @Jolley71717 , thanks for pointing this out. I already have a patch up to address this. Stay tuned for the next release!

**Comment by tzhenghao** [comment]
@Jolley71717 We addressed this in the latest Python SDK v0.7.0 release, so I'm gonna close this.
