### ISSUE TITLE
R410 BOM doesn't match schematic and PCB

### ISSUE THREAD

**Issue by eprast22** [hologram-io/nova-hardware#4]
Hello,

Regarding the Hologram Nova Gerbers:

The following components are listed on the schematic and on the PCB, I don't see these components on the BOM. 

L1, C1, C3, C4, C8, C7, C5, D6, D7, D8, D9.

Can someone help me understand why these are missing? Are these components no longer needed.

Several of these capacitors are used for decoupling and may be optional. But L1 is required as 0 ohm resistor to receive 5V from USB.

Additionally, there are components on the BOM (R11, R51, C43) that are DNI (not populated) on the schematic. Are these components required?

If anyone knows this would be very helpful! Thank you.

**Comment by rbalik** [comment]
Hey, the correct BOM is now in the repo. I'm going to close this, but feel free to open a new issue or post on our forum with any questions.
