### ISSUE TITLE
R410 PWR_ON

### ISSUE THREAD

**Issue by jsuffolk** [hologram-io/nova-hardware#5]
UBlox documentation describes a sequence for activating R410 via PWR_ON signal low. Nova schematic shows PWR_ON linked to pin 2, an undocumented reserved pin. Does anybody know if this is an undocumented way to achieve PWR on automatically when power is applied to the R410 device? Or is there something amiss with the schematic?

**Comment by rbalik** [comment]
Ublox confirmed with us that our method is ok before we went to production. I think the only downside to doing it this way is that if you power it off with CPWROFF then you can't turn it back on without a full power cycle but that's not really a problem for this use case.

**Comment by rbalik** [comment]
Oh also note that the schematic is for the U201. We place a few things a little differently for the R410 (same PCB though). See BOM for more information

**Comment by jsuffolk** [comment]
Thanks, this is pretty helpful. Looking at the R410 Nova board I have, looks like the R51, R11, and C43 are not populated, but the R52 is (presumably the 100K resistor to ground as shown in the schematic). Can you confirm that this is accurate?

**Comment by rbalik** [comment]
I just added the actual BOM for the R410 into this repo so you should be able to see exactly what you need now. I'm gonna go ahead and close this but feel free to open a new issue or post on our forum ( https://community.hologram.io/ ) if you have any more questions.
